package Document.Basics.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Cell = 0;
  public static final int ICanBeReferenced = 1;
  public static final int Image = 2;
  public static final int ImageFile = 3;
  public static final int Paragraph = 4;
  public static final int Reference = 5;
  public static final int Row = 6;
  public static final int Section = 7;
  public static final int Table = 8;
  public static final int TableOfContents = 9;
  public static final int UsePackage = 10;
  public static final int UsePackages = 11;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x968b09380d4f4b45L, 0x9c47d86e2dddb74bL);
    builder.put(0x53b09c58d92e6638L, Cell);
    builder.put(0x53b09c58d93096e9L, ICanBeReferenced);
    builder.put(0xfb8026902fb92cdL, Image);
    builder.put(0xfb8026902fb92d0L, ImageFile);
    builder.put(0xfb8026902faad02L, Paragraph);
    builder.put(0x288f85bc880edab1L, Reference);
    builder.put(0x53b09c58d92e6637L, Row);
    builder.put(0xfb8026902f8247dL, Section);
    builder.put(0x53b09c58d92e6634L, Table);
    builder.put(0xfb80269030445caL, TableOfContents);
    builder.put(0x2f9dbe118972aa3bL, UsePackage);
    builder.put(0x2b10c2e2d3935d68L, UsePackages);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
