package Document.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Cell = 0;
  public static final int Document = 1;
  public static final int ICanBeReferenced = 2;
  public static final int IContentItem = 3;
  public static final int IHasSubContent = 4;
  public static final int Image = 5;
  public static final int ImageFile = 6;
  public static final int Paragraph = 7;
  public static final int Reference = 8;
  public static final int Row = 9;
  public static final int Section = 10;
  public static final int Table = 11;
  public static final int TableOfContents = 12;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0xe9a610efe9344ec5L, 0xaa3d44f7c7af41d2L);
    builder.put(0x53b09c58d92e6638L, Cell);
    builder.put(0xfb8026902f82467L, Document);
    builder.put(0x53b09c58d93096e9L, ICanBeReferenced);
    builder.put(0xfb8026902f8246aL, IContentItem);
    builder.put(0xfb8026902f8246bL, IHasSubContent);
    builder.put(0xfb8026902fb92cdL, Image);
    builder.put(0xfb8026902fb92d0L, ImageFile);
    builder.put(0xfb8026902faad02L, Paragraph);
    builder.put(0x288f85bc880edab1L, Reference);
    builder.put(0x53b09c58d92e6637L, Row);
    builder.put(0xfb8026902f8247dL, Section);
    builder.put(0x53b09c58d92e6634L, Table);
    builder.put(0xfb80269030445caL, TableOfContents);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
